### ISSUE TITLE
redux-store-visualizer depends on unpublished version 0.4.1 of d3-store-visualizer

### ISSUE THREAD

**Issue by wrightmikea** [romseguy/redux-store-visualizer#1]
following the steps in the README fails because d3-store-visulizer latest npm version is 0.3.2

mwright@mwright-mbp:~/github$ mkdir romseguy
mwright@mwright-mbp:~/github$ cd romseguy/
mwright@mwright-mbp:~/github/romseguy$ git clone https://github.com/romseguy/redux-store-visualizer.git
Cloning into 'redux-store-visualizer'...
remote: Counting objects: 64, done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 64 (delta 14), reused 64 (delta 14), pack-reused 0
Unpacking objects: 100% (64/64), done.
Checking connectivity... done.
mwright@mwright-mbp:~/github/romseguy$ cd redux-store-visualizer/
mwright@mwright-mbp:~/github/romseguy/redux-store-visualizer[master]$ npm install
npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: d3-state-visualizer@'>=0.4.1 <0.5.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.2","0.1.0","0.1.1","0.2.0","0.2.1","0.2.2","0.3.0","0.3.1","0.3.2"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'redux-todomvc-example'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mwright/github/romseguy/redux-store-visualizer/npm-debug.log

**Comment by romseguy** [comment]
Thank you, I didn't notice I was publishing to a private npm registry instead of the official one. Fixing now.

**Comment by romseguy** [comment]
Should be good to go!
https://github.com/romseguy/redux-store-visualizer/commit/43c466e31b91ea1709dd0016c6f24a3eb00ad649

**Comment by wrightmikea** [comment]
it worked, thanks
